### ISSUE TITLE
Some initial feedback from the June 17 deployment

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/oduwsdl.github.io#2]
Per the e-mail, here are a few points that I think will help improve the current design.
* Make navigation visible and not behind a hamburger menu unless on mobile. We have the screen real estate.
* People page - make a little more information dense. It currently requires a lot of scrolling.
* Froggie image anti-aliasing (I'll supply a new version)
* Software bg - how about some of our own code as the background instead of a CC image?
* Add streams to homepage - inclusive of Twitter, Flickr, and blag RSS. This ought to be done a little more elegantly than the current version on the CS domain.
* Nav: about, blag, home, people... Home should probably be first or last per convention.
* Press page - can we skin this?
* Software page - needs better ordering than alphabetic. I had changed it at one point to use both pinning and sorting by latest checkin - this would emphasize the currency of the projects' last maintenance.

**Comment by N0taN3rd** [comment]
@machawk1 thanks for the feed back.

> Make navigation visible and not behind a hamburger menu unless on mobile. We have the screen real estate. 

Is there a preference if we use the full name or shorter tagline WS-DL at ODU-CS?
I would assume full name but for clarification sake if others may like both or shorter tagline.

> Nav: about, blag, home, people... Home should probably be first or last per convention.

Thanks for pointing that out. Really did not look at the nav menu to much once I filtered out some internal pages not linkable (main pages link to them and their are alot of them)

> Add streams to homepage - inclusive of Twitter, Flickr, and blag RSS. This ought to be done a little more elegantly than the current version on the CS domain

Agree. Then perhaps the title layout should become the full navigation per first feedback and the homepage and the about page should merge into one. The title layout was more of an stylistic experiment to see if folks liked it.  Then again could put the about pages contents above the tiles. Thoughts on either design choices?

The styling for the Flickr embed matches nicely but the white of the Twitter feed clashes so hard. The [documentation from twitter](https://dev.twitter.com/web/overview/css) states you can style if doing a simple embed but do not see anything on that for [timeline widgets](https://dev.twitter.com/web/embedded-timelines) so may have to resort to using the [dark theme](https://dev.twitter.com/web/embedded-timelines/parameters).

Right now per the blag stream that information is loaded from a yaml file in the _data directory. 
Githube pages only provides RSS feeds for [blogs hosted on the pages](https://help.github.com/articles/atom-rss-feeds-for-github-pages/) so until I whip up some JS to load the RSS feed or find some way to aggregate that information the yaml data entries will have to suffice unless WSDL goes with @ibnesayeed  suggestion and move the blog to github pages which would be awesome as we could use the extra space and rendering/style customization provided to us by github pages. 

> People page - make a little more information dense. It currently requires a lot of scrolling.

210% agree but will have to figure out how to tweak the flex styling to play nice those massive images / shrink them and their contains without jacking up the whole layout or go to another layout.

The harvard lil lab one is nice and will try to emulate that design first before going crazy playing around with styling.

> Froggie image anti-aliasing (I'll supply a new version)

THANKS!

> Press page - can we skin this?

Not sure to sure on this one. From [their docs](http://dev.storify.com/api/stories#custom-css) it looks like you gotta be on their enterprise pay to play level but
there is a [list of classes ](http://answers.livefyre.com/developers/reference/app-customizations/change-display-options/css-classes/storify-css/) used by them. But again its loaded via an iframe. @phonedude did you notice any customization options when setting up that embed? 

> Software page - needs better ordering than alphabetic. I had changed it at one point to use both pinning and sorting by latest checkin - this would emphasize the currency of the projects' last maintenance.

Did attempt it but my unfamiliarity with the liquid templating system did not allow my to convert the datetime fields returned form the [github repo api](https://developer.github.com/v3/repos/) at this time. Jekyll blogs get full access to view the github users repos without making an XHR to api.github so the sorting will have to be done on our end.

**Comment by machawk1** [comment]
> Is there a preference if we use the full name or shorter tagline WS-DL at ODU-CS?
> I would assume full name but for clarification sake if others may like both or shorter tagline.

Spell it out in the first instance (Web Science and Digital Libraries (WS-DL)) then use WS-DL in each subsequent instance. You could additionally use the `abbr` HTML tag to help clarify the latter in the case that a reader doesn't start from the initial definition.

> the homepage and the about page should merge into one...

I think the about and home page should still be separate. Because the streams are updated very often, they ought to be on the home page but given precedence secondarily to the primary information a user might be seeking (nav, who we are, etc).

> move the blog to github pages

I don't foresee that happening. As MLN mentioned, we would likely lose the link history unless some sophisticated rewriting was performed. If the mapping was one-to-one, that would be interesting but a completely independent project from revising the homepage. ;)

@phonedude has some JS to pull in the streams. Is this customizable?

**Comment by phonedude** [comment]
closing this since we have a new version of the page.
