### ISSUE TITLE
Provide a better Froggie image

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/oduwsdl.github.io#3]
A reminder per #2 to provide @N0taN3rd with the image for the homepage.

**Comment by machawk1** [comment]
![froggie](https://user-images.githubusercontent.com/2514780/27299141-503dc138-54f9-11e7-97c7-3103e59ebdad.png)

@N0taN3rd This is the best resolution I have based on the original haphazard Photoshop job. Keeping the image on this color bg might be best for the sake of transparency but crop at will.

**Comment by N0taN3rd** [comment]
@machawk1 received, it will be live soon

**Comment by N0taN3rd** [comment]
@machawk1 added and live
